practice_todayData = {'chamber': 'House', 
'start_date': '2018-02-15', 
'end_date': '2018-02-15', 
'num_results': 2, 
'votes': [{'congress': 115, 
	'chamber': 'House', 
	'session': 2, 
	'roll_call': 80, 
	'source': 'http://clerk.house.gov/evs/2018/roll080.xml', 
	'url': 'http://clerk.house.gov/evs/2018/roll080.xml', 
	'vote_uri': 'https://api.propublica.org/congress/v1/115/house/sessions/2/votes/80.json', 
	'bill': {'bill_id': 'hr620-115', 
		'number': 'H.R.620', 
		'sponsor_id': 'P000592', 
		'api_uri': 'https://api.propublica.org/congress/v1/115/bills/hr620.json', 
		'title': 'To amend the Americans with Disabilities Act of 1990 to promote compliance through education, to clarify the requirements for demand letters, to provide for a notice and cure period before the commencement of a private civil action, and for other purposes.', 
		'latest_action': 'Rules Committee Resolution H. Res. 736 Reported to House. Provides for consideration of H.R. 620 and H.R. 3978 under structured rules and H.R. 3299 under a closed rule. Each bill shall be debatable for one hour. The resolution provides for proceedings during the period of February 16, 2018 through February 23, 2018.'}, 
		'amendment': {}, 
		'question': 'On Passage', 
		'description': 'ADA Education and Reform Act of 2017', 
		'vote_type': 'YEA-AND-NAY', 
		'date': '2018-02-15', 
		'time': '11:56:00', 
		'result': 'Passed', 
		'democratic': {'yes': 12, 
			'no': 173, 
			'present': 0, 
			'not_voting': 8, 
			'majority_position': 'No'}, 
		'republican': {'yes': 213, 
			'no': 19, 
			'present': 0, 
			'not_voting': 6, 
			'majority_position': 'Yes'}, 
		'independent': {'yes': 0, 
			'no': 0, 
			'present': 0, 
			'not_voting': 0},
		 'total': {'yes': 225, 
		 'no': 192, 
		 'present': 0, 
		 'not_voting': 13}}, 

	{'congress': 115, 
		'chamber': 'House', 
		'session': 2, 
		'roll_call': 79, 
		'source': 'http://clerk.house.gov/evs/2018/roll079.xml', 
		'url': 'http://clerk.house.gov/evs/2018/roll079.xml', 
		'vote_uri': 'https://api.propublica.org/congress/v1/115/house/sessions/2/votes/79.json', 
		'bill': {'bill_id': 'hr620-115', 
		'number': 'H.R.620', 
		'sponsor_id': 'P000592', 
		'api_uri': 'https://api.propublica.org/congress/v1/115/bills/hr620.json', 
		'title': 'To amend the Americans with Disabilities Act of 1990 to promote compliance through education, to clarify the requirements for demand letters, to provide for a notice and cure period before the commencement of a private civil action, and for other purposes.', 
		'latest_action': 'Rules Committee Resolution H. Res. 736 Reported to House. Provides for consideration of H.R. 620 and H.R. 3978 under structured rules and H.R. 3299 under a closed rule. Each bill shall be debatable for one hour. The resolution provides for proceedings during the period of February 16, 2018 through February 23, 2018.'}, 
		'amendment': {}, 
		'question': 'On Agreeing to the Amendment', 
		'description': 'Langevin of Rhode Island Part A Amendment No. 2', 
		'vote_type': 'RECORDED VOTE', 
		'date': '2018-02-15', 
		'time': '11:46:00', 
		'result': 'Failed', 
		'democratic': {'yes': 173, 
			'no': 11, 
			'present': 0, 
			'not_voting': 9, 
			'majority_position': 'Yes'}, 
		'republican': {'yes': 15, 
			'no': 215, 
			'present': 0, 
			'not_voting': 8, 
			'majority_position': 'No'}, 
		'independent': {'yes': 0, 
			'no': 0, 
			'present': 0, 
			'not_voting': 0},
		 'total': {'yes': 188, 
		 'no': 226, 
		 'present': 0, 
		 'not_voting': 16}}]}